/**
 * @file mainwindow.h
 * @brief Header file for the MainWindow class.
 *
 * This file declares the MainWindow class, which implements the main interface
 * and user interaction logic for the calculator application.
 */

#ifndef MAINWINDOW_H
#define MAINWINDOW_H

#include <QMainWindow>

QT_BEGIN_NAMESPACE
namespace Ui {
class Calculator;
}
QT_END_NAMESPACE

/**
 * @brief The MainWindow class provides the main interface for the calculator application.
 * 
 * This class handles user interaction through buttons and keyboard input,
 * and it performs the necessary operations to display results.
 */
class MainWindow : public QMainWindow
{
    Q_OBJECT

public:
    /**
     * @brief Constructs the MainWindow object.
     * 
     * @param parent Pointer to the parent widget. Default is nullptr.
     */
    MainWindow(QWidget *parent = nullptr);

    /**
     * @brief Destroys the MainWindow object.
     */
    ~MainWindow();

private:
    /// Pointer to the Calculator UI generated by Qt Designer.
    Ui::Calculator *ui;

    /**
     * @brief Variable to store the first number for operations.
     */
    double firstNum;

    /**
    * @brief Flag to indicate if the second number is being typed.
    */
    bool typingSecondNum = false;

    /**
    * @brief Variable to store the current operation.
    */
    QString currentOperation = "null";

protected:
    /**
     * @brief Handles key press events for keyboard input.
     * 
     * @param event Pointer to the QKeyEvent containing information about the pressed key.
     */
    void keyPressEvent(QKeyEvent *event) override;

private slots:
    /**
     * @brief Slot called when a digit button is pressed.
     */
    void digit_pressed();

    /**
     * @brief Slot called when a binary operation button (+, -, *, /, etc.) is pressed.
     */
    void binary_operation();

    /**
     * @brief Slot called when the decimal point button is released.
     */
    void on_button_point_released();

    /**
     * @brief Slot called when the equals button is released.
     */
    void on_button_equal_released();

    /**
     * @brief Slot called when the clear button (C) is released.
     */
    void on_button_clear_released();

    /**
     * @brief Slot called when the delete button (DEL) is released.
     */
    void on_button_del_released();

    /**
     * @brief Slot called when the factorial button (!) is released.
     */
    void on_button_factorial_released();

    /**
     * @brief Slot called when the logarithm button (log) is released.
     */
    void on_button_logarithm_released();

    /**
     * @brief Slot called when the help button (?) is released.
     */
    void on_button_help_released();

    /**
     * @brief Slot called when the sign change button (+/-) is released.
     */
    void on_button_sign_released();
};
#endif 

/** END OF FILE MAINWINDOW.H*/
