name: MathLib Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake g++ libgtest-dev
      - name: Install Google Test from source
        run: |
            cd /tmp
            git clone https://github.com/google/googletest.git
            cd googletest
            cmake .
            sudo make install

      - name: Build and test
        run: |
          cd build
          cmake ..
          cmake --build .
          ctest --output-on-failure